Ethernet switch manager
Insei/rol pull request #56
Opened 2022-08-29 10:08 UTC by lordspinach

2022-09-08 17:44 UTC, Insei requested changes
Нужно чтоб ты поправил все замечания и Yetus.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +	}
Я думаю ты забыл здесь так же обратится ещё и к менеджеру, что-бы обновить конфигурацию VLAN на свитче.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) isVLANIdUnique(ctx context.Context, vlanID int, switchID uuid.UUID) (bool, error) {
Я думаю функцию надо переименовать в VlanIDIsUniqueWithinTheSwitch()

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	if err != nil {
Проверка err должна быть перед проверкой размера слайса.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	if err != nil {
Если у нас произошла ошибка при создании VLAN на свитче, мы должны удалить сущность VLAN.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) updateVLANsOnPort(ctx context.Context, VLAN dtos.EthernetSwitchVLANDto, updateDto dtos.EthernetSwitchVLANUpdateDto, switchID uuid.UUID) error {
Я думаю было бы лучше переименовать эту функцию в SyncVlanPortsChangesOnSwitch

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +		err = e.vlanRepo.Delete(ctx, vlan.ID)
Здесь мы тоже должны удалять VLANы и со свитча тоже, а после сохранить изменения через switchManager

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) existenceOfRelatedEntitiesCheck(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) error {
Почему existenceOfRelatedEntitiesCheck а не checkExistenceOfRelatedEntities? Вроде во втором варианте повышается читабильность т.к. сразу видно, что это функция проверки.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) portExist(ctx context.Context, switchID, portId uuid.UUID) (bool, error) {
Думаю стоит переименовать функцию в portIsExist

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) dtoPortsExist(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) (bool, error) {
Я думаю, что лучше сделать проверку иначе.
Для начала у тебя есть массив ID'шников портов, на котором VLAN тегирован. Если ты сделаешь запрос (сначала количества, а потом) списка портов в репозитории, через queryBuilder и укажешь все ID-шники тегированных портов через OR, То получив результат, по количеству ты сможешь понять, все ли порты существуют, если каких то нет, но найти не существующий ID и добавить этот ID в сообщение валидации не составит труда. Тоже самое сделать с не тегированными VLAN'ами

Так мы сможем сократить количество запросов к репозиторию, что позитивно скажется на производительности.

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	}
Ты забыл вызвать сохранение изменений через switchManager

2022-09-08 17:44 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) getDifference(a, b []uuid.UUID) []uuid.UUID {
Эта функция нигде не используется, значит надо её удалить

2022-09-09 08:05 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) portExist(ctx context.Context, switchID, portId uuid.UUID) (bool, error) {
ок

2022-09-09 08:07 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) dtoPortsExist(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) (bool, error) {
ок

2022-09-09 08:10 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) isVLANIdUnique(ctx context.Context, vlanID int, switchID uuid.UUID) (bool, error) {
ок

2022-09-09 08:11 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) existenceOfRelatedEntitiesCheck(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) error {
ок

2022-09-09 08:11 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	if err != nil {
ок

2022-09-09 08:11 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	if err != nil {
принял

2022-09-09 08:12 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) updateVLANsOnPort(ctx context.Context, VLAN dtos.EthernetSwitchVLANDto, updateDto dtos.EthernetSwitchVLANUpdateDto, switchID uuid.UUID) error {
согласен

2022-09-09 08:12 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	}
поправлю

2022-09-09 08:13 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +		err = e.vlanRepo.Delete(ctx, vlan.ID)
ок

2022-09-09 08:13 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) getDifference(a, b []uuid.UUID) []uuid.UUID {
ок

2022-09-09 08:14 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +	}
ок

2022-09-09 21:27 UTC, Insei requested changes

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +		_, err = Update[dtos.EthernetSwitchVLANDto](ctx, e.vlanRepo, updDto, vlan.ID, nil)
Я думаю перед обновлением надо задастся вопросом, а нужно ли обновлять VLAN, вдруг порт не состоял в этом VLAN изначально.

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +		_, err = Update[dtos.EthernetSwitchVLANDto](ctx, e.vlanRepo, updDto, vlan.ID, nil)
И если состоял, то нужно так же убрать этот порт из VLAN'a на свитче через switchManager. (убрать тегированный или не тегированный VLAN).

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +		queryBuilder.Or("ID", "==", port.ID())
Нужно создать отдельный queryBuilder, иначе у тебя получается запрос :
"SwitchID", "==", switchID ИЛИ "ID", "==", port.ID ИЛИ и т.д, а надо:
"SwitchID", "==", switchID И ("ID", "==", port.ID ИЛИ ....)

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) dtoPortsExist(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) (bool, error) {
Ну я думаю что лучше переименовать функцию В CheckUnexistedPorts. И булевое значение возвращать смысла нет, у тебя же во всех случаях возвращаются обернутые ошибки, либо внутренние, либо валидации, зачем тут булевое значение возвращать?

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +		return err //we already wrap error
Ну вот я об этом и говорю, зачем булевое значение возвращаешь?

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	err = switchManager.SaveConfig()
Я думаю, что лучше всё таки вывести SaveConfig из метода, и вызывать его после вызова этого метода, иначе происходит путаница, потому что обычно мы вызываем функции по управлению свитча, а затем вызываем функцию сохранения конфига, а тут просто вызываем функцию, что влияет на общее понимание что происходит. Хотя можно просто переименовать метод добавив AndSaveConfig, думаю это даже лучше.

2022-09-09 21:27 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) syncVlanPortsChangesOnSwitch(ctx context.Context, VLAN dtos.EthernetSwitchVLANDto, updateDto dtos.EthernetSwitchVLANUpdateDto, switchID uuid.UUID) error {
Да имя метода и так уже длинное, согласен, но лучше добавить ещё к нему AndSaveConfig, в угоду более правильному описанию что делает функция, я уже написал причину такого ренейминга в другом комменте.

2022-09-12 10:27 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +		_, err = Update[dtos.EthernetSwitchVLANDto](ctx, e.vlanRepo, updDto, vlan.ID, nil)
принял

2022-09-12 10:29 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +		queryBuilder.Or("ID", "==", port.ID())
хорошо

2022-09-12 10:31 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) dtoPortsExist(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) (bool, error) {
ок

2022-09-12 10:31 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +		return err //we already wrap error
исправлю

2022-09-12 10:36 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +	err = switchManager.SaveConfig()
сделаю по первому варианту

2022-09-12 10:39 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) syncVlanPortsChangesOnSwitch(ctx context.Context, VLAN dtos.EthernetSwitchVLANDto, updateDto dtos.EthernetSwitchVLANUpdateDto, switchID uuid.UUID) error {
как и в прошлом замечании, вынесу сохранение из метода

2022-09-12 10:39 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +		queryBuilder.Or("ID", "==", port.ID())
хорошо

2022-09-12 15:24 UTC, Insei requested changes
И надо вернуться обратно на uuid для VLAN, т.к. мы поддерживаем стандарт, там где можем: ID - это UUID.
И поправь конфликт с тестом, иначе Yetus не запустится.

2022-09-12 15:24 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +	for _, tPort := range vlan.TaggedPorts {
Можешь использовать utils.SliceContainsElement()

2022-09-12 15:24 UTC, Insei commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) CheckNonexistentPorts(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) error {
Почему эта функция экспортная(публичная)?

2022-09-12 15:24 UTC, Insei commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) VlanIDIsUniqueWithinTheSwitch(ctx context.Context, vlanID int, switchID uuid.UUID) (bool, error) {
Почему эта функция тоже публичная? это же явно внутренняя логика.

2022-09-12 15:24 UTC, Insei commented on src/webapi/controllers/EthernetSwitchVLANGinController.go
> +// @param vlanID path int true "Ethernet switch ID"
Поправь описание.

2022-09-12 18:29 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +func (e *EthernetSwitchService) CheckNonexistentPorts(ctx context.Context, switchID uuid.UUID, dto dtos.EthernetSwitchVLANBaseDto) error {
ctrl+c, ctrl+v с твоего замечания, исправлю

2022-09-12 18:30 UTC, lordspinach commented on src/app/services/EthernetSwitchServiceVLAN.go
> +func (e *EthernetSwitchService) VlanIDIsUniqueWithinTheSwitch(ctx context.Context, vlanID int, switchID uuid.UUID) (bool, error) {
аналогично

2022-09-12 18:30 UTC, lordspinach commented on src/webapi/controllers/EthernetSwitchVLANGinController.go
> +// @param vlanID path int true "Ethernet switch ID"
хорошо

2022-09-12 18:31 UTC, lordspinach commented on src/app/services/EthernetSwitchServicePorts.go
> +	for _, tPort := range vlan.TaggedPorts {
ок

2022-09-15 10:26 UTC, Insei requested changes

2022-09-15 10:26 UTC, Insei commented on docs/plantuml/controllers/EthernetSwitchVLANGinController.puml
> +        -service *services.EthernetSwitchPortService
*services.EthernetSwitchPortService я думаю, тут должен быть EthernetSwitchService
Так же я предполагаю, что надо изменить EthernetSwitchPortGinController тоже самое, если это ещё не сделано

2022-09-15 10:26 UTC, Insei commented on src/webapi/controllers/EthernetSwitchVLANGinController.go
> +// @param vlanID path string true "Ethernet switch VLAN ID"
Я думаю тут стоит переименовать VlanID в VlanUUID, чтоб не было путаницы

2022-09-15 10:26 UTC, Insei commented on src/webapi/controllers/EthernetSwitchVLANGinController.go
> +// @param vlanID path string true "Ethernet switch VLAN ID"
Ну и во всех остальных местах тоже.

2022-09-15 10:36 UTC, lordspinach commented on docs/plantuml/controllers/EthernetSwitchVLANGinController.puml
> +        -service *services.EthernetSwitchPortService
ок

2022-09-15 10:36 UTC, lordspinach commented on src/webapi/controllers/EthernetSwitchVLANGinController.go
> +// @param vlanID path string true "Ethernet switch VLAN ID"
ок

2022-09-25 23:45 UTC, Insei requested changes
Нужно добавить тесты репозитория VLAN и сервиса VLAN.

2022-10-03 05:20 UTC, Insei commented
Принято

2022-10-03 05:20 UTC, closed without merging