Host network bridge
Insei/rol pull request #57
Opened 2022-09-08 15:00 UTC by lordspinach

2022-09-08 18:31 UTC, Insei requested changes
В целом всё хорошо, но не вижу обновление схем и схем контроллера нового, поправь все замечания, и доделай схемы.

2022-09-08 18:31 UTC, Insei commented on src/infrastructure/HostNetworkManager_linux.go
> +func (h *HostNetworkManager) SetLinkNoMaster(linkName string) error {
Я думаю лучше переименовать эту функцию в UnsetLinkMaster, так вроде лучше будет читабильность, т.к. у нас есть функция SetLinkMaster, так же её описание лучше изменить на Unset master for link, но можно посмотреть на алтернативные по типу ResetMasterLink

2022-09-08 18:31 UTC, Insei commented on src/infrastructure/HostNetworkManager_linux.go
> +		} else if h.vlanExistInConfig(config, inter.GetName()) {
Почему мы тут имеем дела с VLAN, ходя загружаем бриджы?

2022-09-08 18:31 UTC, Insei commented on src/tests/HostNetworkBridgeService_test.go
> +//func Test_HostNetworkVlanService_CreateBridgeWithNotExistedMasterInterface(t *testing.T) {
Я думаю это здесь тоже лишнее

2022-09-08 18:31 UTC, Insei commented on src/tests/HostNetworkBridgeService_test.go
> +var (
Сделай пожалуйста структуру как это сделано в тестах менеджера

2022-09-08 18:31 UTC, Insei commented on src/tests/HostNetworkVlanService_test.go
>  var (
Можешь тоже пожалуйста сделать отдельную структуру теста

2022-09-08 18:31 UTC, Insei commented on src/app/mappers/EntityDtoMapper.go
> +		//HostNetworkBridge
Поправь табуляцию, она ни в чём не виновата)

2022-09-09 08:15 UTC, lordspinach commented on src/app/mappers/EntityDtoMapper.go
> +		//HostNetworkBridge
вернем не место

2022-09-09 08:16 UTC, lordspinach commented on src/infrastructure/HostNetworkManager_linux.go
> +func (h *HostNetworkManager) SetLinkNoMaster(linkName string) error {
согласен, поправлю

2022-09-09 08:17 UTC, lordspinach commented on src/infrastructure/HostNetworkManager_linux.go
> +		} else if h.vlanExistInConfig(config, inter.GetName()) {
опечатка, поправлю

2022-09-09 08:17 UTC, lordspinach commented on src/tests/HostNetworkBridgeService_test.go
> +var (
да, ок

2022-09-09 08:18 UTC, lordspinach commented on src/tests/HostNetworkBridgeService_test.go
> +//func Test_HostNetworkVlanService_CreateBridgeWithNotExistedMasterInterface(t *testing.T) {
ага, забыл

2022-09-09 08:18 UTC, lordspinach commented on src/tests/HostNetworkVlanService_test.go
>  var (
ок

2022-10-03 05:21 UTC, Insei commented
Принято

2022-10-03 05:21 UTC, closed without merging